name: MarvelQL CI/CD

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:12.16.1

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          yarn install
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build --tag back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USERNAME }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USERNAME }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/back:latest